
spring:
  profiles:
    active:
    - dev

---

server: 
  port: 8021
  servlet:
    context-path: /provider

mybatis: 
  config-location: classpath:mybatis/mybatis-config.xml             # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.microservice.common.entity      # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                             # mapper映射文件

spring: 
  profiles: dev
  application:
    name: atguigu-microservice-config-provider-dept
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver                        # mysql驱动包
    url: jdbc:mysql://localhost:3306/atguigu_microservice_1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true         # 数据库名称
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource                    # 当前数据源操作类型

eureka:
  client:
    service-url:
      defaultZone: http://eureka7011.com:7011/config/eureka/server
  instance:
    instance-id: atguigu-microservice-config-provider-dept:8021
    prefer-ip-address: true
    status-page-url-path: ${server.servlet.context-path}/actuator/info
 
info:  
  app.name: atguigu-microservice
  company.name: www.atguigu
  build.artifactId: $project.artifactId$
  build.version: $project.version$


---

server: 
  port: 8022
  servlet:
    context-path: /provider

mybatis: 
  config-location: classpath:mybatis/mybatis-config.xml             # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.microservice.common.entity      # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                             # mapper映射文件

spring: 
  profiles: test
  application:
    name: atguigu-microservice-config-provider-dept
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver                        # mysql驱动包
    url: jdbc:mysql://localhost:3306/atguigu_microservice_2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true         # 数据库名称
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource                    # 当前数据源操作类型

eureka:
  client:
    service-url:
      defaultZone: http://eureka7011.com:7011/eureka/
  instance:
    instance-id: atguigu-microservice-config-provider-dept:8022
    prefer-ip-address: true
    status-page-url-path: ${server.servlet.context-path}/actuator/info
 
info:  
  app.name: atguigu-microservice
  company.name: www.atguigu
  build.artifactId: $project.artifactId$
  build.version: $project.version$

