spring:
  profiles:
    active:
    - dev

---

server: 
  port: 9032
  servlet:
    context-path: /config/client

spring: 
  profiles: dev
  application:
    name: microservice-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
 
server: 
  port: 9033
  servlet:
    context-path: /config/client

spring: 
  profiles: test
  application:
    name: microservice-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
